export const ciekawostki = [
  {
    text: "Polscy producenci gier planszowych stają się coraz bardziej zauważalni i konkurencyjni na rynku europejskim. Europejski rynek gier planszowych stale rośnie, a prognozy wskazują, że do roku 2023 osiągnie on wartość prawie 3,5 miliardów euro. Liderami na europejskim rynku gier planszowych są Niemcy, gdzie wartość rynku szacuje się na ok 400 mln EUR. Niemcy specjalizują się w projektowaniu i wydawaniu tzw. eurogier. Jest to rodzaj gier planszowych cechujących się relatywnie prostymi zasadami, stosunkowo krótkim czasem gry, dosyć wysokim poziomem abstrakcji oraz bardzo ograniczoną interakcją między graczami (np. Puerto Rico, Wsiąść do Pociągu).",
  },
  {
    text: "Z pewnością arcytrudnym zadaniem jest wyobrażenie sobie ogromu wszechświata, a jakiekolwiek próby ogarnięcia tego myślą, zazwyczaj kończą się smutkiem, spowodowanym faktem, jak nieistotni jesteśmy, jako jednostka, wobec potęgi kosmosu. Jeszcze trudniejszym zadaniem jest wyobrażenie sobie olbrzymiej liczby możliwości rozegrania partii szachowej. Liczba ta, nazywana liczbą Shanonna wynosi 10^120! Na podstawie średniej gęstości materii oraz atomów, zdołaliśmy obliczyć, że atomów we wszechświecie jest tylko 10^80. A więc możliwości na rozegranie partii szachowej jest 10^40 razy więcej! Claude Shannon, dokonując tych obliczeń, chciał udowodnić, że komputer nie jest w stanie przeanalizować każdego możliwego ruchu, ponieważ nawet gdyby obliczał jedną grę na mikrosekundę, zajęłoby mu to dłużej niż będzie istniał nasz Układ Słoneczny. Gdybyśmy analizowali tylko te partie szachowe, w których obie strony chcą wygrać, to liczba możliwości rozegrania partii szachowej jest szacowana na 10^46.",
  },
  {
    text: "Gra GO jest najbardziej rozbudowaną grą planszową na świecie. Partię możemy rozegrać na 10^365 sposobów. Biorąc pod uwagę ogrom tej liczby, to nawet najlepsze superkomputery na świecie nie są w stanie przewidzieć wszystkich możliwości rozegrania partii. Dlatego gra GO jest jedyną grą na świecie, do której nie powstał symulator na tyle rozwinięty, by wygrywać regularnie wszystkie partie. Z pomocą dla branży IT może przyjść komputer kwantowy. W popularnym eksperymencie, superkomputer IBM, uważany za najlepiej rozwinięty na świecie, wyliczył, że potrzebuje 10 000 lat na wykonanie pewnych obliczeń kwantowych, natomiast komputer kwantowy dał odpowiedź po 3 minutach i 20 sekundach.",
  },
  {
    text: "Najsłynniejszy geniusz świata, Albert Einstein, nie był fanem gier. W wywiadzie dla New York Timesa z 1936, powiedział nawet, że nie ma czasu na takie rozrywki. Zbyt ważna była dla niego praca, która pochłaniała prawie cały jego czas. W szachy jednak grywał, głównie za sprawą swojego serdecznego przyjaciela, Emanuela Laskera, mistrza świata w szachach, który tytuł ten zachowywał najdłużej w historii – 26 lat i 337 dni! Słynna jest zwłaszcza szachowa partia Einsteina z Oppenheimerem. Einstein zniszczył przeciwnika świetną taktyczną wizją i zmusił Oppenheimera do rezygnacji po zaledwie 24 ruchach.",
  },
];
