export const gry = [
  {
    id: 1,
    maxGraczy: 4,
    minGraczy: 2,
    maxCzas: 30,
    minCzas: 20,
    minWiek: 12,
    tytul: "Hero Realms",
    link: "https://www.ceneo.pl/80903217",
    trudnosc: 1.91,
    wydawca: "Wise Wizard Games",
    gatunek: "Strategia,Deckbuilder",
    opis: "Nadszedł czas bohaterów! Możesz zostać bohaterem i dokonywać imponujących czynów i rekrutować potężnych Czempionów do walki po Twojej stronie! Gra ta jest stworzona przez twórców bestsellerowej gry Star Realms, Hero Realms łączy w sobie emocje z interakcji, typowe dla klasycznych karcianych gier kolekcjonerskich, z przyjemnością budowania własnej talii w trakcie gry. Wykorzystuj złoto, kupując kolejne karty akcji i Czempionów, by rozbudować nimi swoją talię. Karty te po zagraniu wspomogą Cię swoimi potężnymi efektami, dając Ci dodatkowe złoto oraz generując punkty walki, którymi możesz atakować przeciwników bądź ich Czempinów. Jeżeli pozbawisz przeciwnika wszystkich punktów życia – wygrywasz!",
    ocena: 7.6,
    zdj: "https://cf.geekdo-images.com/6xc4TuJynN5o_ZF0fHOdAA__imagepage/img/g_LTpAvnnINRqjkCvsVqqY2GPo4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6162556.png",
  },
  {
    id: 2,
    maxGraczy: 4,
    minGraczy: 2,
    maxCzas: 45,
    minCzas: 20,
    minWiek: 13,
    trudnosc: 2.2,
    wydawca: "Brotherwise Games",
    gatunek: "Strategia,Deckbuilder",
    ocena: 7,
    link: "https://www.ceneo.pl/82401267",
    tytul: "Boss Monster",
    zdj: "https://cf.geekdo-images.com/-YFlvRWqGqvMk3QqSPugNA__imagepage/img/ihmBA5bP-B5QhilH7GLdCokKSrs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4163700.png",
    opis: "Nadchodzą nowi zawodnicy! W bitwie przeciwko nieugiętym bohaterom minibossowie stanowią ostateczną broń. Powstanie minibossów to najnowsze i najobszerniejsze wydanie bestsellerowej gry karcianej o budowaniu podziemi. Jeśli pierwszy raz sięgasz po Boss Monstera, ten zestaw stanowi doskonałe rozpoczęcie. Jeśli jesteś doświadczonym łowcą bohaterów, będziesz zadowolony z większej liczby nowych opcji taktycznych niż kiedykolwiek wcześniej!Zdobywaj monety, korzystając z nieznanych dotąd komnat i czarów. Używaj monet, aby wzmacniać komnaty i zdolności albo najmować i rozwijać potężnych minibossów. Czas zbudować najbardziej zabójcze podziemia w historii. Czas na powstanie minibossów!",
  },
  {
    id: 3,
    maxGraczy: 2,
    minGraczy: 2,
    maxCzas: 40,
    minCzas: 30,
    minWiek: 10,
    trudnosc: 2.22,
    tytul: "7 Cudów Świata Pojedynek",
    ocena: 8.1,
    link: "https://www.ceneo.pl/40299955",
    wydawca: "Repos Production",
    gatunek: "Strategia,Ekonomiczna",
    zdj: "https://cf.geekdo-images.com/WzNs1mA_o22ZWTR8fkLP2g__imagepage/img/G8mf2eXt4iRho5TL2N5207oQ5lI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3376065.jpg",
    opis: "Poprowadź swoją cywilizację ku świetności, dbając o jej rozwój militarny i naukowy oraz konstruując niezwykle Budowle i Cuda. 7 cudów świata: pojedynek istnieją 3 drogi do zwycięstwa: dominacja militarna, dominacja naukowa i zwycięstwo cywilne. Gra wprowadza nowatorski sposób dobierania kart, rozwoju naukowego i konfliktów militarnych oraz zawiera 12 różnych cudów, zapewniając wiele różnorodnych i angażujących rozgrywek.",
  },
  {
    id: 4,
    maxGraczy: 5,
    minGraczy: 3,
    maxCzas: 60,
    minCzas: 30,
    minWiek: 14,
    trudnosc: 1.65,
    tytul: "Szeryf z Nottingham",
    ocena: 7.1,
    link: "https://www.ceneo.pl/54263722",
    wydawca: "Arcane Wonders",
    zdj: "https://cf.geekdo-images.com/BBgLFKUzr6tcKtlIM2JSFw__imagepage/img/_3bSh9NeLxkL23XBruNlzxk5QCM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2075830.jpg",
    gatunek: "Losowa,Towarzyska,Interakcja",
    opis: "Ekscytująca gra o kłamstwie, przekupstwie i przemycie. Jako przebiegły kupiec pragniesz zarobić jak najwięcej na swoich towarach. Aby to zrobić, musisz najpierw przechytrzyć niesławnego Szeryfa z Nottingham. Zabawna, szybka i wciągająca gra, „Szeryf z Nottingham” z pewnością zagości u Was na wiele wieczorów.",
  },
  {
    id: 5,
    maxGraczy: 4,
    minGraczy: 2,
    maxCzas: 90,
    minCzas: 45,
    minWiek: 10,
    trudnosc: 2.22,
    tytul: "Vikings Gone Wild",
    ocena: 7.2,
    link: "https://www.ceneo.pl/53719825",
    wydawca: "Corax Games",
    zdj: "https://cf.geekdo-images.com/JE64fVnmk5_Pctb1H-M-pw__imagepage/img/3hImpwtSAhSwCNeAOhhsX1GwDD0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3145803.png",
    gatunek: "Strategia,Deckbuilder",
    opis: "W Vikings Gone wild gracze wcielają się w role przywódców poróżnionych klanów. Klany te walczą ze sobą, by udowodnić bogom, który z nich jest najpotężniejszy. W każdej turze gracze zagrywają karty z ręki, aby kupować jednostki i umocnienia, konstruować budowle i atakować przeciwników. Do zwycięstwa konieczne jest odnalezienie właściwej równowagi pomiędzy rozwojem ekonomicznym, a militarnym.",
  },
  {
    id: 6,
    maxGraczy: 6,
    minGraczy: 2,
    maxCzas: 15,
    minCzas: 5,
    minWiek: 13,
    trudnosc: 1.41,
    tytul: "Światowy Konflikt",
    ocena: 7,
    link: "https://www.ceneo.pl/31007865",
    wydawca: "Indie Boards",
    zdj: "https://www.profit24.pl/images/editor/ZABAWKI/Foksal/FoxGames/5907078169781_1.jpg",
    gatunek: "Imprezowa,Towarzyska",
    opis: "Walka o wpływy, pieniądze i władzę! Akcja gry toczy się na granicy rosyjskiej i zachodniej strefy wpływów. Gracze wcielają się w lokalnych polityków starających się sięgnąć po władzę. Aby to osiągnąć, muszą skutecznie wykorzystać swoje wpływy w kraju i za granicą.",
  },
  {
    id: 7,
    maxGraczy: 4,
    minGraczy: 1,
    maxCzas: 90,
    minCzas: 45,
    minWiek: 10,
    trudnosc: 2.79,
    tytul: "Osadnicy: Królestwa Północy",
    ocena: 7.6,
    link: "https://www.ceneo.pl/83411621",
    wydawca: "Portal Games",
    gatunek: "Strategia,Deckbuilder",
    zdj: "https://cf.geekdo-images.com/w6HMeWkxsTJM6zC8oxwUfQ__itemrep/img/J4VbPpo78R7OOp6Erk2y_3GGd0o=/fit-in/246x300/filters:strip_icc()/pic4543694.jpg",
    opis: "Osadnicy z trzech imperiów Północy ruszają na podbój nowych lądów. Są głodni zasobów, złaknieni chwały, skupieni na ciągłym rozwoju. Kluczem do sukcesu ich wypraw jest rozbudowa infrastruktury, wykorzystanie zmiennych kolei losu i przechytrzenie przeciwników. Królestwa Północy to samodzielna gra karciana zaprojektowana przez weterana branży gier, Ignacego Trzewiczka. Można wybrać można talie, w których w rolach głównych występują: Wikingowie, Inuici lub Szkoci.",
  },
  {
    id: 8,
    maxGraczy: 4,
    minGraczy: 2,
    maxCzas: 40,
    minCzas: 20,
    minWiek: 8,
    trudnosc: 1.8,
    tytul: "Santorini",
    ocena: 7.5,
    link: "https://www.ceneo.pl/67906856",
    wydawca: "Rolexey",
    zdj: "https://cf.geekdo-images.com/665Ply7Ho1WVf1v1iZlWeg__itemrep/img/8vG-UtGeFbhMXPTzLDUOqWot8hA=/fit-in/246x300/filters:strip_icc()/pic3283110.png",
    gatunek: "Strategia,Familijna,Logiczna",
    opis: "Polega na budowaniu kolejnych poziomów wież, a zwycięża osoba, która jako pierwsza wdrapie się na najwyższy z nich. Łączy w sobie proste zasady, przejrzystą mechanikę dającą wiele możliwości przeprowadzenia rozgrywki, rewelacyjne i wzorowo wkomponowane ilustracje oraz kilka trybów gry. Świetnie sprawdza się jako gra dwuosobowa. Nazwę gry zaczerpnięto od greckiej wyspy, której, zapierający dech w piersiach widok, przypomina animacje wykorzystane w planszówce.",
  },
  {
    id: 9,
    maxGraczy: 2,
    minGraczy: 2,
    maxCzas: 45,
    minCzas: 15,
    minWiek: 8,
    trudnosc: 1.2,
    tytul: "Statki",
    ocena: 6,
    link: "https://www.ceneo.pl/94038974",
    wydawca: "brak",
    zdj: "https://a.allegroimg.com/original/110f17/37e3dd8041f68d51da29e28d14e6/GRA-PLANSZOWA-STATKI-OKRETY-WOJNA-MORSKA-BITWA",
    gatunek: "Familijna",
    opis: "gra strategiczno-planszowa dla dwóch osób. Wynaleziona przez Clifforda Von Vicklera na początku XX wieku, a opatentowana przez Milton Bradley Company w 1943 roku. Gra jest znana w wielu krajach pod nazwą: gra w Statki lub Salvo. W polskiej literaturze można się też spotkać z nazwą: wojna morska lub bitwa morska.",
  },
  {
    id: 10,
    maxGraczy: 10,
    minGraczy: 3,
    maxCzas: 60,
    minCzas: 20,
    minWiek: 8,
    trudnosc: 1.33,
    tytul: "Sabotażysta",
    link: "https://www.ceneo.pl/3880300",
    ocena: 6.6,
    wydawca: "AMIGO",
    gatunek: "Imprezowa,Familijna",
    opis: " Wspaniała rozrywka przeznaczona dla 3 do 10 graczy w wieku od 8 lat. Już dziś przekonaj się o sile światowego fenomenu, grając ze znajomymi w tę fantastyczną grę karcianą! W trakcie rozgrywki, uczestnicy zabawy wcielą się w żądne bogactwa krasnoludy. Kopiąc tunele, będą próbowały dostać się do bryłek złota. Zadanie nie jest tak proste, jak się wydaje. Wśród kopaczy znajduje się sabotażysta! Rozbita latarnia, połamany kilof, wykolejony wózek lub zawalony tunel? To z pewnością wina sabotażysty, który nie cofnie się przed niczym, by zagarnąć całe złoto.",
    zdj: "https://cf.geekdo-images.com/0vJwP6NGa7GHPZKC3gplUw__itemrep/img/aJcXGhYr8XxyKEK6EqbG0bePrOk=/fit-in/246x300/filters:strip_icc()/pic3989824.jpg",
  },
];
